# Generated by Django 2.2.3 on 2019-08-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('recently_added', models.DateTimeField(auto_now_add=True)),
                ('audi', models.FileField(blank=True, default=None, upload_to='audio/')),
                ('notes', models.FileField(blank=True, default=None, upload_to='notes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sermons.Category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sermons.Teacher')),
            ],
        ),
    ]
