# Generated by Django 2.2.3 on 2019-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audi',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='notes',
            field=models.FileField(blank=True, upload_to='notes/'),
        ),
    ]
