# Generated by Django 2.2.3 on 2019-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_auto_20190801_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audi',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='notes',
            field=models.FileField(blank=True, default=None, null=True, upload_to='notes/'),
        ),
    ]
