# Generated by Django 2.2.3 on 2019-08-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_auto_20190801_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audi',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='notes',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
