# Generated by Django 2.2.3 on 2019-08-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0006_auto_20190802_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('by_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sermons.Teacher')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
